FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IHByb21ldGhldXMtYXBiCmRlc2NyaXB0aW9uOiBJbnN0YWxsIHBy\
b21ldGhldXMKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAp0YWdzOgogIC0gbW9iaWxl\
LXNlcnZpY2UKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IFByb21ldGhldXMKICBpbWFnZVVybDog\
Imh0dHBzOi8vYXZhdGFyczEuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvMzM4MDQ2Mj9zPTIwMCZ2\
PTQiCiAgZG9jdW1lbnRhdGlvblVybDogImh0dHBzOi8vcHJvbWV0aGV1cy5pby9kb2NzL2ludHJv\
ZHVjdGlvbi9vdmVydmlldy8iCiAgcHJvdmlkZXJEaXNwbGF5TmFtZTogIlJlZCBIYXQsIEluYy4i\
CiAgc2VydmljZU5hbWU6IHByb21ldGhldXMKcGxhbnM6CiAgLSBuYW1lOiBkZWZhdWx0CiAgICBk\
ZXNjcmlwdGlvbjogVGhpcyBkZWZhdWx0IHBsYW4gZGVwbG95cyBwcm9tZXRoZXVzLWFwYgogICAg\
ZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJhbWV0ZXJzOiBbXQ=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
