{
 "title": "Mobile Security Metrics",
 "tags": [ "mobile-security-metrics" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appId",
    "label": "App",
    "query": "select distinct data->'app'->>'appId' from mobileappmetrics where event_type='security';"
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": "select distinct data->'device'->>'platform' from mobileappmetrics where event_type='security';"
   },
   {
    "name": "checkType",
    "label": "Check Type",
    "query": "select distinct (all_checks.chk->>'name') from (select jsonb_array_elements(data->'security') chk from mobileAppMetrics WHERE $__timeFilter(event_time) AND event_type='security') as all_checks;"
   },
   {
    "name": "resolutionInterval",
    "label": "Resolution",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "content": "# Mobile Security Metrics\n\nThis dashboard shows Self-Defence Security Check results per platform. Select the platform and application using the dropdowns above."
  },
  {
   "title": "Passed check %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  cast((select sum(case when (securityCheck->>'passed')::boolean then 1 else 0 end)) as decimal) / cast(count(*) as decimal) * 100\nFROM\n  (SELECT jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Check count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM\n  (SELECT jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Unique clients w/ checks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT clientId)\nFROM\n  (SELECT clientId, jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Apps w/ checks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(DISTINCT appId)\nFROM\n  (SELECT data->'app'->>'appId' as appId, jsonb_array_elements(data->'security') as securityCheck\n    FROM mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n  ) as checksRaw\nWHERE securityCheck->>'name' like $checkType;"
    }
   ]
  },
  {
   "title": "Fails per check type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  checks.entry->>'name' as checkName,\n  count(*)\nFROM\n(\n  SELECT jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY checkName;"
    }
   ]
  },
  {
   "title": "Fails per app",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  appId,\n  count(*)\nFROM\n(\n  SELECT data->'app'->>'appId' as appId, jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY appId;"
    }
   ]
  },
  {
   "title": "Fails per platform",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  platform,\n  count(*)\nFROM\n(\n  SELECT data->'device'->>'platform' as platform, jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY platform;"
    }
   ]
  },
  {
   "title": "Fails per check type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(checks.event_time, $resolutionInterval),\n  checks.entry->>'name' as checkName,\n  count(*)\nFROM\n(\n  SELECT event_time, jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY checkName, time;"
    }
   ]
  },
  {
   "title": "Fails per app",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(checks.event_time, $resolutionInterval),\n  appId,\n  count(*)\nFROM\n(\n  SELECT event_time, data->'app'->>'appId' as appId, jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY appId, time;"
    }
   ]
  },
  {
   "title": "Fails per platform",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(checks.event_time, $resolutionInterval),\n  platform,\n  count(*)\nFROM\n(\n  SELECT event_time, data->'device'->>'platform' as platform, jsonb_array_elements(data->'security') as entry\n    FROM mobileAppMetrics\n  WHERE $__timeFilter(event_time)\n    AND event_type='security'\n    AND data ? 'security'\n    AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n    AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n) as checks\nWHERE checks.entry->>'passed' = 'false'\n  AND checks.entry->>'name' like $checkType\nGROUP BY platform, time;"
    }
   ]
  },
  {
   "title": "Top Offending Clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    latestEntryInTimeRange.clientId as \"Client Id\",\n    latestEntryInTimeRange.data->'app'->>'appId' as \"App\",\n    latestEntryInTimeRange.data->'app'->>'appVersion' as \"App Version\",\n    latestEntryInTimeRange.data->'app'->>'sdkVersion' as \"SDK Version\",\n    latestEntryInTimeRange.data->'device'->'platform' as \"Platform\",\n    latestEntryInTimeRange.data->'device'->>'platformVersion' as \"Platform Version\",\n    failCount as \"Fail Count\"\nFROM\n(\n  SELECT clientId, count(*) as failCount\n  FROM\n    (SELECT\n        clientId,\n        jsonb_array_elements(data->'security') as entry\n      FROM mobileAppMetrics\n      WHERE $__timeFilter(event_time)\n        AND event_type='security'\n        AND data ? 'security'\n        AND data ? 'app' AND data->'app' ? 'appId' and data->'app'->>'appId' like $appId\n        AND data ? 'device' AND data->'device' ? 'platform' and data->'device'->>'platform' like $platform\n    ) as checks\n  WHERE checks.entry->>'passed' = 'false'\n    AND checks.entry->>'name' like $checkType\n  GROUP BY clientId\n  ORDER BY failCount desc\n  LIMIT 10\n) clientFails\nJOIN\n(\n  select entry.clientId, entry.event_time, entry.data\n    from mobileAppMetrics entry\n    inner join\n      (select clientId, max(event_time) as latestEntryTime\n        from mobileAppMetrics\n        WHERE $__timeFilter(event_time)\n          and event_type='security'\n        group by clientId\n      )\n      latestEntry\n      on entry.clientId = latestEntry.clientId and entry.event_time = latestEntryTime\n      where event_type='security'\n) latestEntryInTimeRange\nON clientFails.clientId = latestEntryInTimeRange.clientId\nORDER BY \"Fail Count\" desc;"
    }
   ]
  }
 ]
}