{
 "title": "Mobile Security Metrics",
 "time": { "from": "2018-03-20T14:09:11.167Z", "to": "2018-03-20T14:09:24.657Z" },
 "templating": {
  "list": [
   {
    "name": "appId",
    "label": "App",
    "query": "select distinct data->'app'->>'appId' from mobileappmetrics;"
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": "select distinct data->'device'->>'platform' from mobileappmetrics;"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 1 },
   "content": "# Mobile Security Metrics\n\nThis dashboard shows Self-Defence Security Check results per platform. Select the platform and application using the dropdowns above."
  },
  {
   "title": "Passed check % [Platform: $platform, App: $appId]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT now() as time, sum(passed)/sum(total) * 100 as perc_passed from (\n  SELECT (select sum(case when (sec->>'passed')::boolean then 1 else 0 end)\n  from jsonb_array_elements(s.data->'security') as sec) as passed,\n  jsonb_array_length(s.data->'security') as total\n  FROM mobileAppMetrics as s\n  INNER JOIN (\n    SELECT DISTINCT a.clientId\n    FROM mobileAppMetrics as a\n    WHERE a.data->'app'->>'appId' like $appId\n    AND a.data->'device'->>'platform' like $platform\n  ) as apps ON (s.clientId = apps.clientId)\n  group by s.data, s.event_time\n  HAVING $__timeFilter(s.event_time)\n) as totals\n"
    }
   ]
  },
  {
   "title": "Security Check Count  [Platform: $platform, App: $appId]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT now() as time, sum(check_count) as value\nFROM (\n    SELECT jsonb_array_length(s.data->'security') as check_count\n    FROM mobileAppMetrics as s\n    INNER JOIN (\n      SELECT DISTINCT a.clientId\n      FROM mobileAppMetrics as a\n      WHERE a.data->'app'->>'appId' like $appId\n      AND a.data->'device'->>'platform' like $platform\n    ) as apps ON (s.clientId = apps.clientId)\n    group by s.data, s.event_time\n    HAVING $__timeFilter(s.event_time)\n  ) AS check_totals"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, sum(passed) as passed, sum(not_passed) as not_passed\nfrom (SELECT event_time as time,\n  (select sum(case when (sec->>'passed')::boolean then 1 else 0 end)\n  from jsonb_array_elements(data->'security') as sec) as passed,\n  (select sum(case when (sec->>'passed')::boolean then 0 else 1 end)\n  from jsonb_array_elements(data->'security') as sec) as not_passed\nFROM mobileAppMetrics) as t\nWHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Totals per Platform [App: $appId]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, platform as metric, sum(case when passed then 1 else 0 end) as passed\nfrom (\n  select s.clientId, platform, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId, data->'device'->>'platform' as platform\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    },
    {
     "rawSql": "select now() as time, platform || ' not passed' as metric, sum(case when passed then 0 else 1 end) as passed\nfrom (\n  select s.clientId, platform, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId, data->'device'->>'platform' as platform\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    }
   ]
  },
  {
   "title": "Details [Platform: $platform, App: $appId]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "platform"
  },
  {
   "title": "Top Offending Clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select client, appId as app, appVersion as \"version\", sdkVersion, platformVersion, sum(not_passed) as failed_checks from\n(\n  select s.clientId as client,\n  (\n    select sum(case when (sec->>'passed')::boolean then 0 else 1 end)\n      from jsonb_array_elements(s.data->'security') as sec\n  ) as not_passed,\n  a.*\n  from mobileAppMetrics AS s\n  INNER JOIN (\n    SELECT DISTINCT ON (clientId)\n    clientId,\n    data->'app'->>'appId' as appId,\n    data->'app'->>'appVersion' as appVersion,\n    data->'app'->>'sdkVersion' as sdkVersion,\n    data->'device'->>'platform' as platform,\n    data->'device'->>'platformVersion' as platformVersion\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n  WHERE $__timeFilter(s.event_time)\n) as t\ngroup by client, appId, appVersion, sdkVersion, platformVersion\nORDER BY sum(not_passed) DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Totals per Check Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, name as metric, sum(case when passed then 1 else 0 end) as passed\nfrom (\n  select s.clientId, name, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    },
    {
     "rawSql": "select now() as time, name || ' not passed' as metric, sum(case when passed then 0 else 1 end) as passed\nfrom (\n  select s.clientId, name, passed from \n  (\n    select * from (\n      select clientId, jsonb_array_elements(data->'security') as sec\n      FROM mobileAppMetrics\n      where $__timeFilter(event_time)\n    ) as securityRecords,\n    jsonb_to_record(sec) as x(name text, passed boolean)\n  ) AS s\n  INNER JOIN (\n    SELECT DISTINCT clientId\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n) as t\ngroup by metric"
    }
   ]
  },
  {
   "title": "Metrics History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select event_time as time, sum(passed) as passed, sum(not_passed) as not_passed\nfrom (\n  SELECT event_time,\n  (select sum(case when (sec->>'passed')::boolean then 1 else 0 end)\n  from jsonb_array_elements(data->'security') as sec) as passed,\n  (select sum(case when (sec->>'passed')::boolean then 0 else 1 end)\n  from jsonb_array_elements(data->'security') as sec) as not_passed\n  FROM mobileAppMetrics as s\n  INNER JOIN (\n    SELECT DISTINCT clientId\n    FROM mobileAppMetrics\n    where data->'app'->>'appId' like $appId\n    and data->'device'->>'platform' like $platform\n  ) as a ON (s.clientId = a.clientId)\n  where $__timeFilter(event_time)\n) as check_counts\ngroup by event_time"
    }
   ]
  }
 ]
}