- name: Scaling down grafana deployment
  k8s_extensions_v1beta1_deployment:
    name: grafana
    namespace: '{{ namespace }}'
    replicas: 0
    state: present

- name: Removing grafana deployment
    k8s_extensions_v1beta1_deployment:
      name: grafana
      namespace: '{{ namespace }}'
      state: absent

- name: Scaling down prometheus deployment
  k8s_extensions_v1beta1_deployment:
    name: prometheus
    namespace: '{{ namespace }}'
    replicas: 0
    state: present

- name: Removing prometheus deployment
    k8s_extensions_v1beta1_deployment:
      name: prometheus
      namespace: '{{ namespace }}'
      state: absent

- name: Scaling down aerogear-app-metrics deployment
  k8s_extensions_v1beta1_deployment:
    name: aerogear-app-metrics
    namespace: '{{ namespace }}'
    replicas: 0
    state: present

- name: Removing aerogear-app-metrics deployment
    k8s_extensions_v1beta1_deployment:
      name: aerogear-app-metrics
      namespace: '{{ namespace }}'
      state: absent

- name: Scaling down postgres deployment
  k8s_extensions_v1beta1_deployment:
    name: postgres
    namespace: '{{ namespace }}'
    replicas: 0
    state: present

- name: Removing postgres deployment
    k8s_extensions_v1beta1_deployment:
      name: postgres
      namespace: '{{ namespace }}'
      state: absent

- k8s_v1_secret:
    name: '{{ prometheus_secret_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: '{{ prometheus_configmap_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: '{{ grafana_ini_configmap_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: '{{ grafana_datasources_configmap_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: '{{ grafana_dashboards_configmap_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: grafana-dashboards-providers-configmap
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service_account:
    name: '{{ proxy_serviceaccount_name }}'
    namespace: '{{ namespace }}'
    state: absent

- name: Prometheus PVC
  k8s_v1_persistent_volume_claim:
    name: '{{ prometheus_claim_name}}'
    namespace: "{{ namespace }}"
    state: absent

- name: Grafana PVC
  k8s_v1_persistent_volume_claim:
    name: '{{ grafana_claim_name}}'
    namespace: "{{ namespace }}"
    state: absent

- name: Postgres PVC
  k8s_v1_persistent_volume_claim:
    name: '{{ postgres_claim_name}}'
    namespace: "{{ namespace }}"
    state: absent