- name: Delete all prometheus resources by app label (limited to buildconfig,deploymentconfig,service,imagestream,route and pod)
  shell: oc delete all -l app=prometheus -n '{{ namespace }}'

- name: Delete all grafana resources by app label (limited to buildconfig,deploymentconfig,service,imagestream,route and pod)
  shell: oc delete all -l app=grafana -n '{{ namespace }}'

- k8s_v1_secret:
    name: prometheus
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: prometheus-configmap
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: grafana-ini-configmap
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: grafana-datasources-configmap
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_config_map:
    name: grafana-dashboards-configmap
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service_account:
    name: oauth-proxy
    namespace: '{{ namespace }}'
    state: absent

- name: Prometheus PVC
  k8s_v1_persistent_volume_claim:
    name: prometheus-claim
    namespace: "{{ namespace }}"
    state: absent

- name: Grafana PVC
  k8s_v1_persistent_volume_claim:
    name: grafana-claim
    namespace: "{{ namespace }}"
    state: absent