= Verifying Self-Defence Security Check Results utilizing the metrics service

This guide shows how to use Security Checks metrics to gather valueable information regarding the shape of the environment users run your mobile apps in, in relation to security risks that can lead to attack vectors against the data that is stored in-device.

[discrete]
== Prerequisites

* An App that is using the AeroGear SDK (link TODO)
* A running Metrics Service (link TODO)
* An OpenShift account that will provide access to Grafana in the Metrics Service (link TODO)

[discrete]
== Accessing visualisations

The visualisation for Security Checks metrics is done via set of Grafana dashboards, which in turn query the datasources for Security Checks metrics.

The visualisations are spread across different dashboards:

* Mobile Services Dashboard (Summary data in the 'Mobile Security Metrics' section)
* Mobile Security Metrics Dashboard

In general, the summary data that is visible on the 'Mobile Services' Dashboard is also available on the 'Mobile Security Metrics' dashboard, but in more detail.

[discrete]
== Analyzing Security Check Passing totals

At the top level of the summary, general passing percentages for checks and totals regarding the amount of checks run are shown.

These indicate the overall secureness of the environments your apps are running in, however since these totals are aggregated across all apps, platforms and clients a smaller overall percentage of passing checks does not imply that the clients are insecure as a whole, but can instead reflect a small amount of frequent users on a particularly insecure setup.

[discrete]
== Analyzing Failures per Check Type

Following the above totals it is possible to see the amount of failures per type of check. These checks can vary in their scope and how critical they are to your App.
Refer to the mobile app SDK documentation for details on each type of Security Check and implications of them failing.

[discrete]
== Analyzing Failures per App

Each App can have different concerns related to the Security Check types, for instance an App that requires faithful geolocalization data would need to avoid running in a device with Developer Mode elabled or in an Emulator where that data could be spoofed. As such this measurement can help making decisions towards changing the implementation of an App to disallow these environments and implement defences on different layers of the solution, i.e. the back-end server.

[discrete]
== Analyzing Failures per Platform

Each Platform will potentially have unique Security Check types due to their unique characteristics, so being able to visualise these per Platform is useful to focus on their specifics. Also it is quite likely that an installation of an App that violates a set of Security Checks is present in a given Platform, so this visualisation helps quickly identifying and focusing on such offenders.

[discrete]
== Analyzing Offending Clients

In the more detailed Mobile Security Metrics Dashboard it is possible to see the individual top offending clients in regards to most failed number of Security Checks.
Since security check metrics are most often sent once per initialization of the App (despite this being implementation-specific), this view highlights clients that not necessarily fail the most different kinds of Checks, but that do those most often, thus having the highest likelyhood of these failures leading to actual security breaches.

[discrete]
== Additional Resources

* 
