apiVersion: v1
kind: Secret
metadata:
  name: "{{ prometheus_secret_name }}-{{ CLIENT_ID }}"
  namespace: "{{ namespace }}"
  labels:
    mobile: enabled
    name: "{{ prometheus_secret_name }}-{{ CLIENT_ID }}"
    clientId: "{{ CLIENT_ID }}"
    serviceName: "{{ prometheus_secret_name }}"
stringData:
  clientId: "{{ CLIENT_ID }}"
  config: "{}"
  name: "{{ prometheus_secret_name }}"
  type: "{{ prometheus_secret_name }}"
  uri: "{{ METRICS_URI }}"
